// USER REVIEW TESTING

###
GET http://localhost:8081/userReview/getReviews/70051
Content-Type: application/json


###
GET http://localhost:8081/userReview/getReviews
Content-Type: application/json

###
POST http://localhost:8081/userReview/reviews
Content-Type: application/json 

{
 "stationId": "70051",
  "recommendation": "Recommended",
  "description": "very clean!",
  "user": "jakebailes"
}

###
DELETE http://localhost:8081/userReview/deleteReviews/65de11bc29a120d0a026ac86
Content-Type: application/json 

###


// USER FAVORITES TESTING

POST http://localhost:8081/userFav/userFavorite
Content-Type: application/json 

{
  "user": "65a6e8d8eb6db7b9a7217a0c",
  "stationId": 70234
}

### 

GET http://localhost:8081/userFav/getFavorites/65a6e8d8eb6db7b9a7217a0c
Content-Type: application/json 

### 

GET http://localhost:8081/userFav/getFavorites
Content-Type: application/json 



### 
DELETE http://localhost:8081/userFav/deleteFavorites/65a6e8d8eb6db7b9a7217a0c/70234
Content-Type: application/json

###

// REVIEW RATINGS TESTING
###
POST http://localhost:8081/reviewRating/rateReview/65df0e0ef26b5859cec39f1d
Content-Type: application/json

{
  "thumbsUp": 1
}

### 
GET http://localhost:8081/reviewRating/getRatings/65df0e0ef26b5859cec39f1d

###
GET http://localhost:8081/reviewRating/getAllRatings

###
DELETE http://localhost:8081/reviewRating/deleteRating/65df0e0ef26b5859cec39f1d
